### ISSUE TITLE
Схема — дерево видов

### ISSUE THREAD

**Issue by krauklish** [RusPosevkin/evolution#11]
Я обсудил общий вид схемы с Ильей. В ней могут появиться небольшие стилистические изменения (пунктир вместо плотной линии, например, или другие цвета) или слегка подвинуться отдельные части. Но принципиальная конструкция измениться не должна. Поэтому, думаю, можно начать её делать.

**Comment by krauklish** [comment]
Добавил ветки, см. https://github.com/RusPosevkin/evolution/pull/23

**Comment by RusPosevkin** [comment]
Задача выглядит завершенной
