### ISSUE TITLE
Настроить скорость прокрутки интерактивного таймлайна

### ISSUE THREAD

**Issue by RusPosevkin** [RusPosevkin/evolution#13]
Как только будет финальный вариант с расположением всех блоков и общей шириной страницы, можно делать задачу. 

Сейчас скорость прокрутки линейная, а нужно что-то вроде экспоненциальной. Похоже, будет много хардкода.

**Comment by krauklish** [comment]
Посмотрел сейчас линейную версию, всё очень круто 🥇 

Вброшу, что в идеальном варианте увеличивается не только скорость прокрутки, но и ширина розового окошка. Это не самый приоритетный функционал, но будет круто, если получится.

При этом, если возникнут сложности, можно пофлексить и остановиться на упрощенном варианте. Статичная часть таймлайна остается логарифмической, а прокрутка на протяжении всей длины становится линейной. Это не слишком корректно математически, но сгодится, если аккуратно подписать, что к чему. 

Финальный вариант на подходе.

**Comment by krauklish** [comment]
Мы обсудили с Ильей, что неплохо будет и по упрощенному варианту. Т.е. прокрутка линейная и движется с фиксированной скоростью. Теперь надо ее сделать визуально линейной, это я на днях сделаю.

**Comment by krauklish** [comment]
Обновил макет в инвижне, там видно, как примерно будет выглядеть линейный таймлайн:
https://projects.invisionapp.com/d/main#/console/10928005/233210350/inspect

Будет очень круто, если получится сделать это сегодня, потому что тогда можно будет показать Илье. Но я понимаю, что планы могут быть другие :)

**Comment by RusPosevkin** [comment]
Настроил, чтобы периоды на таймлайне и minimap совпадали в процессе прокрутки страницы.
Можно больше заморочиться с более идеальной настройкой синхронизации, но основная задача выглядит вполне достигнутой.
