### ISSUE TITLE
Прикрутить домен

### ISSUE THREAD

**Issue by krauklish** [RusPosevkin/evolution#16]
Для начала я его должен выбрать и купить.

А дальше, похоже, нужен владелец репозитория.

**Comment by krauklish** [comment]
Я зарегал домен, надо подключить.

По-моему, это где-то в настройках, к которым у меня доступа нет. Если там что-то еще надо с моей стороны прописать, то скажи, я сделаю.

**Comment by RusPosevkin** [comment]
@krauklish Вот help по настройке кастомного домена.
https://help.github.com/articles/using-a-custom-domain-with-github-pages/
Тут требуется настройка в админке у твоего регистратора, где ты приобрел домен. И напиши сам домен, я его вобью в настройках репозитория.

**Comment by krauklish** [comment]
Сначала, похоже, нужно в настройках добавить.
Адрес — human-evolution.net

UPD. Я у себя настроил записи. Как я понимаю, если сейчас включить в настройках, то всё должно работать (ну, когда обновится).

**Comment by RusPosevkin** [comment]
It works!
![2017-05-24_23-47-57](https://cloud.githubusercontent.com/assets/1483747/26424880/7a7c129c-40db-11e7-8b33-532cb38df36d.png)
