### ISSUE TITLE
Горизонтально-вертикальный скролл

### ISSUE THREAD

**Issue by RusPosevkin** [RusPosevkin/evolution#21]
После добавления `horizontal-scroll.js` очень багово работает горизонтальный скролл на маке. 
Либо дерганно, либо вообще скроллится в другую сторону. 

Как одно из решений – отключить горизонтальный скролл оставив только вертикальный.

Также есть ощущение, что стало как-то медленней все скроллиться, но это неточно – надо проверять

**Comment by krauklish** [comment]
Да, есть проблема с тачпадом. Надо, видимо, вырубить горизонтальный совсем.

Скорость настраивается в скрипте, но я не могу подобрать подходящую. То слишком медленно, то слишком быстро.

**Comment by krauklish** [comment]
Я не знаю, что тут делать, мне просто не хватает знаний.

Мой скрипт отрабатывает на `wheel`. С мышкой все четко. С тачпадом не получается. Вертикальные движения обрабатываются по `wheel` и скроллят горизонтально. Горизонтальные движения работают по умолчанию и тоже скроллят, из-за этого все дергается.

Как отключить горизонтальное движение на тачпаде, я не знаю.

**Comment by RusPosevkin** [comment]
@krauklish В https://github.com/RusPosevkin/evolution/commit/1ae8030529dd0890f0f6afbeb242738794b4b363 сменил библиотеку  по преобразованию вертикального скролла в горизонтальный. Откровенные лаги ушли. Плюс начало все скроллиться с нормальной скоростью.
P.S. Очень бесило, что скрипт не давал скролить с нужной скоростью, а решал за тебя как нужно. Теперь все хорошо :)
