### ISSUE TITLE
Окошко прокрутки не видно в Сафари

### ISSUE THREAD

**Issue by krauklish** [RusPosevkin/evolution#24]
Прям вот совсем не видно, не знаю, что тут происходит.

![image](https://cloud.githubusercontent.com/assets/4632118/26465223/210cf5d8-4193-11e7-9c22-4d15c99f727b.png)

**Comment by krauklish** [comment]
Вроде как поправил, но как-то наугад. Пока сойдет, но не закрываю.

**Comment by RusPosevkin** [comment]
Лучше указывать коммит или серию коммитов, в которых ты предположительно пофиксил баг. 
Сейчас окно в минимапе видно, закрываем баг. 
Если снова появится, то переоткроем этот же
