### ISSUE TITLE
Зафиксировать минимэп внизу окна

### ISSUE THREAD

**Issue by krauklish** [RusPosevkin/evolution#30]
Я вернул дефолтную прокрутку и добавил минимальную высоту страницы. Теперь на окне, ниже 690px включается вертикальная прокрутка. Само решение не самое элегантное, но пока ладно. При этом есть проблема.

Поскольку позиция интро-минимэпа зависит от размеров окна, он не всегда примагничивается к низу. Я добавил в скрипт примитивную поддержку минимальной высоты, но этого недостаточно: при маленьком окне основная часть фиксируется у нижнего края, а интро болтается за краем, внизу страницы. Иногда, наоборот, оно сползает куда-то кверху. Короче, я запутался совсем.

Я хочу, чтобы весь минимэп всегда фиксировался внизу, а страница жила своей жизнью где-то под ним. Т.е. выглядел прямо как элемент окна.

**Comment by krauklish** [comment]
Вот, я даже нарисовал, как надо: 
![img_0993](https://cloud.githubusercontent.com/assets/4632118/26547164/59045f68-4476-11e7-9768-17231d6c7e0c.JPG)

**Comment by RusPosevkin** [comment]
@krauklish Вроде в https://github.com/RusPosevkin/evolution/commit/5556285f65df3b4f1a9884581f372e55caa53ab7 сделал как ты просил. Проверь, все ли ок, верно ли я тебя понял :)

**Comment by krauklish** [comment]
![image](https://cloud.githubusercontent.com/assets/4632118/26555444/bd10fc4c-449d-11e7-9829-872bfced89f8.png)
У меня сейчас вот так в нижней части :)

**Comment by krauklish** [comment]
↑ Это, конечно, если уменьшить размер окна, а потом проскролить вниз.

**Comment by RusPosevkin** [comment]
@krauklish Добавил суровых костылей и вроде работает как нужно, проверь.

Весь minimap у нас fixed. Проблема заключалась в том, что при горизонтальном скролле, у нас должна прокручиваться intro часть, при этом при вертикальном скролле она же должна прилипать к нижней части экрана (что достигается fixed позиционированием). Все конфликтующие манипуляции со стилями я перенес в скрипты, вместо прокрутки intro части при горизонтальном скролле, она просто сдвигается через left-позиционирование. 
Короче, это жесть, но она работает. 

Сейчас еще приведу все сделанные изменения в нормальный вид и тогда закрою багу

**Comment by RusPosevkin** [comment]
fixed in https://github.com/RusPosevkin/evolution/commit/cb00719d813b8a17a875c3e6d3d4b629b136ee5a

**Comment by krauklish** [comment]
works like a charm 👍 

Я еще увеличил немного нижний отступ у дерева, чтобы фиксированный таймлайн на него не налезал. Теперь у нас достаточно сносный уровень адаптивности по вертикали
