### ISSUE TITLE
Добавить мобильную версию 

### ISSUE THREAD

**Issue by krauklish** [RusPosevkin/evolution#31]
Я еще подумал-посмотрел и хочу все-таки сделать масштабирование, о котором говорил. А через медиазапросы буквально чуть-чуть подправить в мелочах. Идея в том, чтобы уместить страницу в экран телефона по высоте. Поскольку шрифт большой, все будет видно.

То есть я хочу получить примерно такой эффект: 
![iphone](https://cloud.githubusercontent.com/assets/4632118/26607693/6e58cc02-45a0-11e7-8480-e395544a2e28.png)
(Минимэп растягивается на 100% окна)

Если я всё правильно понял, этого можно добиться, задав для `viewport` уменьшенный `initial-scale`. В нашем случае минимальная высота страницы — 690пк, а минимальная высота устройства — допустим, 570пк. Это значит, что нам нужен `height=device-height` (потому что для нас адаптивной является высота, а не ширина, как обычно) и `initial-scale=0.8`. 

Но это не главное. Гораздо важнее, что сейчас у нас на телефонах что-то глобально неправильно с minimap. Скрипт или еще что-то превращают его просто в адовую кашу, которая занимает че-то типа половину длины экрана. А надо растягивать, как на десктопе.

Короче, надо разобраться, как тут всё правильно сделать, чтобы не прописывать миллион медиазапросов :)

**Comment by RusPosevkin** [comment]
Здесь вроде все основное сделали. Осталась небольшая проблема с тем, что на iPhone 5 основной текст залазит на древо видов.
@krauklish здесь нужно будет немного уменьшить шрифт основного текста для мобильного устройства, этого должно быть достаточно.

**Comment by krauklish** [comment]
Я сейчас сделал для вьюпорта `initial-scale=0.65` и добился того эффекта, который хотел изначально. Думаю, что эту можно закрыть, тем более, что для проблем минимапа есть своя задача.
