### ISSUE TITLE
Добавить «таскание» в прокрутку-минимэп

### ISSUE THREAD

**Issue by krauklish** [RusPosevkin/evolution#32]
Настоятельное пожелание Бирмана: научить наш минимэп работать как полноценный скроллбар. Чтобы можно было тянуть мышкой за розовое окошко, и оно бы двигалось. 

Есть шансы?

**Comment by krauklish** [comment]
Крутняк! Но есть два замечания. 

Штука не работает, пока мы не проскролим до основного минимэпа. А значит, ей нельзя воспользоваться сразу, от начала страницы. Я понимаю, почему это так, но это сильно усложняет процесс. Можно ли хотя бы технически сделать, чтобы она работала сразу по загрузке? Например, как только мы за нее схватимся в «нулевом» положении, нас принудительно проскроллит до «точки старта», а дальше уже все пойдет как надо.

А второе замечание ерундовое: на окошечке нужен курсор drag, чтобы рука такая хватающая появлялась.

**Comment by RusPosevkin** [comment]
Ничего себе! Я вот один в один хотел тебе предложить такую же реализацию :)

**Comment by krauklish** [comment]
Надо только там чуть-чуть плавности добавить, если получится. Чтоб он не совсем резко перебрасывал, а так типа за четверть секунды.

**Comment by RusPosevkin** [comment]
Ага, так и планирую.

**Comment by RusPosevkin** [comment]
@krauklish Исправил.
Может быть стоит как-то пользователю дать понять, что окно минимапа интерактивное?
Например, для десктопного пользователя показывать анимашку кликающего курсора возле окна. А после того как прокрутились до стартовой точки  – показать анимашку курсора с перетаскиванием. 
Вроде того, как на лендингах подсказывают, что нужно скроллить.

**Comment by krauklish** [comment]
У меня не работает :)

Но если я правильно понимаю, как должно работать, то это чуточку не так, как я хочу. Я бы хотел, чтобы весь процесс, от начала и дальше, выглядел как единое целое. То есть сразу можно было бы «схватить», и уже в момент захвата (onMouseDown?) нас бы перекидывало в начало.

**Comment by RusPosevkin** [comment]
Там происходит переход по клику. 
Очень странное поведение, если ты хватаешь элемент, а тебя  пробрасывает вперед. Я бы удивился :) С кликом выглядит как-то более предсказуемо. 

Также надо учитывать то, что элемент остался в перетаскиваемом положении и пока тебя пробрасывает вперед, то элемент тоже двигается вперед и ты тебя дополнительно еще на половину минимапа  пробрасывает вперед.

**Comment by krauklish** [comment]
Ну вот да, у меня не происходит перехода. Ни на сайте, ни локально. Хром.

Поведение, на самом деле, примерно такое же странное, как если и просто кликнуть и внезапно перелететь куда то. Проблема в том, что сейчас получается режимность: в одном положении работает так, а в другом — по-другому. Это не хорошо. Если б я кликнул и меня перебросило куда-то, то я бы подумал, что надо кликать, а не таскать. Возможно, даже на разницу в курсорах не обратил бы внимание.

>Также надо учитывать то, что элемент остался в перетаскиваемом положении и пока тебя пробрасывает вперед, то элемент тоже двигается вперед и ты тебя дополнительно еще на половину минимапа пробрасывает вперед.

Вот это реальная проблема. Если ее можно избежать, то надо сделать по моей схеме.

**Comment by krauklish** [comment]
И еще один аргумент: раз уж мы спрятали скроллбар, то эта штука реально должна работать, как скроллбар. Дернуть страницу скроллбар хотя бы теоретически может, а вот двигать куда-то по клику — нет.

**Comment by RusPosevkin** [comment]
Попробуй почистить кеш.
Safari, Chrome, Safari mobile, Chrome mobile – все завелось.

**Comment by RusPosevkin** [comment]
> Вот это реальная проблема. Если ее можно избежать, то надо сделать по моей схеме.

Как раз по твоей схеме и возникает эта проблема

**Comment by RusPosevkin** [comment]
> И еще один аргумент: раз уж мы спрятали скроллбар, то эта штука реально должна работать, как скроллбар. Дернуть страницу скроллбар хотя бы теоретически может, а вот двигать куда-то по клику — нет.

Это мы с тобой обсуждали и договорились, что так не делаем.

**Comment by krauklish** [comment]
>Как раз по твоей схеме и возникает эта проблема

Ну да, я имею в виду, что если можно избежать этой проблемы, делая по моей схеме, то надо делать по моей схеме. То есть это единственное реальное препятствие, но я бы хотел его избежать.

>Это мы с тобой обсуждали и договорились, что так не делаем.

Я не о том. Я имел в виду, что наше нынешнее решение — кликнуть, чтобы страница проехала, а потом тащить за элемент — совсем не похоже на нативный скроллбар. Там, если кликать на «лифт», страница никуда не сдвинется.

**Comment by krauklish** [comment]
Не заводится в хроме: не помогают чистка кэша, инкогнито-режим, перезапуск браузера. Не знаю, че у меня не так :(

В фаерфоксе тоже не завелось, но и хрен с ним.

Речь только про переброску вначале. Само таскание отлично везде работает.

**Comment by RusPosevkin** [comment]
В Firefox, кстати, у меня тоже не завелось. Сейчас заведу багу

**Comment by krauklish** [comment]
Проверил в хроме с другого компа, всё хорошо. Что-то у меня тут глобально не чистится, наверно.
