### ISSUE TITLE
Оптимизировать css

### ISSUE THREAD

**Issue by krauklish** [RusPosevkin/evolution#33]
То, о чем писал в телеграме. Надо бы научиться выкидывать лишние классы. А то я пытаюсь по 10 кб на каждой картинке сэкономить, а у нас style.css на 500 :)

**Comment by krauklish** [comment]
А можем еще вот такую штуку внедрить? 
https://github.com/ben-eb/gulp-uncss

Я так понимаю, она выкинет лишние селекторы. Это, по-моему, 90% нашего css: у нас очень много классов для сетки, которые нигде не используются.

**Comment by RusPosevkin** [comment]
Да, я пробовал его прикрутить. Но там то ли что-то не завелось, то ли он не работал как надо.

**Comment by krauklish** [comment]
О, а расскажи ради интереса, че он тебе показывает? 

Я пробовал сам, у меня вот так: 
![image](https://user-images.githubusercontent.com/4632118/27044131-32ea5690-4fa5-11e7-863c-eab958d3145e.png)
Я не очень шарю в галпе и всяких этих штуках, поэтому даже не стал особо разбираться.

**Comment by RusPosevkin** [comment]
А я пробовал это еще до того, как сам первый раз багу закрыл.
Вроде в начале тоже была ошибка как у тебя. Потом разобрался с этим, показывалось, что все отработало, но ненужные классы в итоговом css по прежнему оставались.

**Comment by krauklish** [comment]
А не помнишь, как ты решил первоначальную проблему? Я просто не понимаю вообще, что он от меня хочет. По идее, уж хоть как-то он должен отрабатывать прямо из коробки.

**Comment by RusPosevkin** [comment]
Там вроде когда указал только `html: ['index.html']`, то заработало.
Не очень мне понятна логика работы этого инструмента, когда указываешь там в массиве для  html ссылку на сайт. Ну я сильно и не углублялся.
