### ISSUE TITLE
Появляется вертикальный скролл

### ISSUE THREAD

**Issue by krauklish** [RusPosevkin/evolution#5]
Сейчас страница чуть торчит вниз и появляется вертикальный скролл. Такого быть не должно.

Насколько я понимаю, происходит вот что. Высота страницы 100vh. Поскольку она длинная, браузер ставит *горизонтальный* скролл-бар. Он закрывает часть страницы, поэтому она не помещается целиком.

Видимо, надо, чтоб высота страницы учитывала ещё ширину горизонтального скролл-бара.

**Comment by RusPosevkin** [comment]
Да, тоже заметил эту проблему, только забыл багу завести. 

Причину ты верно описал, дело действительно в скроле и vh
