### ISSUE TITLE
Интерактивный таймлайн

### ISSUE THREAD

**Issue by krauklish** [RusPosevkin/evolution#7]
_Видеоверсия того, что написано ниже, здесь: https://www.youtube.com/watch?v=ACJKSOkGedw
Макет здесь: https://projects.invisionapp.com/d/main#/console/10928005/233160509/preview_ 

### Статичная линейная шкала (*линейка*)

Период: 0 — 7 млн лет назад, масштаб 1px = 1000 лет, прижата к верхней границе экрана.

### Интерактивная логарифмическая шкала (*таймлайн*)

Период (видимые границы): 10 тыс. — 1 млрд лет назад, масштаб адаптивный, прижата к нижней части.

Таймлайн делится на две части. Статичная часть — до 7 млн (т.е. до начала линейки). Эта часть привязана к вступительной части страницы (заголовок, первый абзац) и скроллится вместе с ней.

Интерактивная часть — от 7 млн и далее —*прокрутка*. По ней двигается окошко-маркер, которое отмечает на таймлайне видимые значения линейки.

Когда при скролле вперед левая граница экрана совпадает с отметкой в 7 млн на таймлайне, шкала должна фиксироваться, а окошко — продолжать движение.

Масштаб шкалы рассчитывается так: прокрутка должна помещаться в 1 экран. По сути, 6990000 лет (в логарифмическом масштабе) = 100vh.

### Known issues

Не считал, но чувствую, что тут не все гладко с масштабированием: если у нас узкий вьюпорт (телефон), все слипнется. Может быть, стоит сильно упрощать (убирать?) эту штуку на маленьком экране.

Еще мне сложно представить, насколько трудно все это считать на лету. Я, конечно, не яваскрипт, но у меня уже голова болит. 

В общем, прикинь и пиши, какие есть опасения.

**Comment by RusPosevkin** [comment]
@krauklish Для мобильной версии, скорее всего, надо будет оставлять только даты, без подписей.

Эту задачу закрываю,таймлайн реализован. Здесь остается настроить скорость прокрутки окна таймлайна – вынес в отдельную задачу https://github.com/RusPosevkin/evolution/issues/13

**Comment by RusPosevkin** [comment]
fixed in https://github.com/RusPosevkin/evolution/commit/766bf7d53e918a47c4932fcf3f93aabfcab033a6

**Comment by krauklish** [comment]
Хорошая идея с датами — можно считать рабочей версией. Но, возможно, достаточно будет убрать не все лейблы, а только половину; короче, я это пока оставляю на самый конец.
